### ISSUE TITLE
Marquee Masking

### ISSUE THREAD

**Issue by Nightasy** [ousnius/BodySlide-and-Outfit-Studio#106]
Would be nice to be able to mask using a Marquee selection.

**Comment by ousnius** [comment]
That would be awesome, along with a lot of other things that would be awesome.
Before I'd do this, I'd implement a proper vertex edit mode, though, which this could then be a part of.

Tons of work to do all that. We have to code things like these from scratch, including all the algorithms and rendering, since we don't have any frameworks to use like Max/Maya/whatever have.

**Comment by ousnius** [comment]
Closing for now as vertex selection was implemented. It doesn't provide the full functionality of something like marquee masking, but it has to suffice for now.
