### ISSUE TITLE
Groups not loading

### ISSUE THREAD

**Issue by flipperbw** [ousnius/BodySlide-and-Outfit-Studio#118]
When I enter the groups screen, or try to filter on them, nothing shows up. If I save a new one, it shows up until I close the window, then disappears again.

They're all present in the folder, and I can manually load them in to edit them. See the gif:

http://i.imgur.com/8m5wvdF.gifv

**Comment by ousnius** [comment]
This is intended behavior. There will be no groups showing up in the UI until you open a groups file. It was done this way because groups are saved in multiple XML files, so they have to be loaded, displayed and saved separately.

If all groups were showing always, you wouldn't have a way of saying which groups are saved in what files. Also, the same group can be expanded in multiple XML files.
