### ISSUE TITLE
Feature request: Update preview window when selecting outfit on Choose Output Set interface 

### ISSUE THREAD

**Issue by CyberFlexie** [ousnius/BodySlide-and-Outfit-Studio#161]
Feature request:

Lost of armor/clothing mods overlap in replacing the vanilla items and thus try to overwrite the same file when batch building. So when looking at the "Choose output set" window (if overwrite warning is enabled in settings), we have to choose which to select. But i have installed so much stuff that I cannot visualize/remember how that specific outfit looks like... 

The current solution is to go back and look ik up or do builds on one group at a time but i might still replace an already better looking outfit because it's hard to keep track of the numerous outfits installed. So here is what comes to mind:

-When looking at the "Choose output set" window, have the Preview window update with the outfit selected (or use modifier keys like control-click)
-or have a setting that allows opening a second preview window when having to select output sets (so that ppl with slow pc's can leave the option off)
-or have little thumbnails generated so you can just choose one for each row of outfits.

**Comment by ousnius** [comment]
I thought about it for a while, but there's no proper way I can implement this into the current program that would be user-friendly and stable.

I can't use the existing preview window and making a whole new feature for showing previews on the side of the window is something that takes up too much of my time for the use case.

You should look at the outfits beforehand and then make your own groups using the group manager, so that you can filter by your new group and only build the outfits you want.

**Comment by CyberFlexie** [comment]
So I picked up the game (FO4) again and modded it from scratch again, but I am running into the same issue again. Making my own groups takes forever and bodyslide does not prevent me from adding conflicting outfits to lists nor warns me if I might have forgotten a non conflicting one... 

How about when you batch build, when clicking on a conflict it runs a command like: BodySlide.exe -previewOnly "outfitA" -p "Selected Preset" && BodySlide.exe -previewOnly "outfitB" -p "Selected Preset"

And also nice if Bodyslide ccould create a new group based on the choices I made? Or have it remember previous choices in a config file or something?
