### ISSUE TITLE
Feature Request: do batch build in separate thread to prevent locking interface

### ISSUE THREAD

**Issue by CyberFlexie** [ousnius/BodySlide-and-Outfit-Studio#162]
Can you move the batch build to it's own thread/proces so that we can continue to use bodyslide while it's building? I know i could just open the program twice but it would be neater if it could be pushed to another (headless) instance or something.

**Comment by ousnius** [comment]
This isn't something I can do, other actions in the program would collide with the batch build process (you could even re-save projects in OS while they build).

I've already made it so batch building uses up all available CPU threads for the x64 build some time ago so that it's way faster, so using BodySlide would simply lock up the program anyway.
