### ISSUE TITLE
Some issues about segments editing in Fallout 4

### ISSUE THREAD

**Issue by StrangerInStrangeLand** [ousnius/BodySlide-and-Outfit-Studio#200]
I wrote them in the nexus but no one seems to care, so I came here with videos.

1. Adding a project or nif file while opening segment tab on right side occurs freezing or fatal exception error. Please watch the video for details.

    https://youtu.be/dG8VfCbBBLs

2. BodySlide and Outfit Studio can't change the segment setting of Wastelander02(Scavenger Outfit or hooded Explorer Outfit in game) nif files.

     https://youtu.be/pPcKojEmO8M

     I like 'leggy' outfit so I create projects to zap the pants of default outfits and put leg mesh(of CBBE Reduced) and panties mesh(from CBBE Underwear of Old Skyrim) in them. And it works fine with the other outfits, but not with Wastelander02 and its hooded version. Please watch the video for details.

**Comment by ousnius** [comment]
1. is fixed, 2. happens because the NIF doesn't have all of its triangles assigned to one of the segments. I don't know of a smart way to automatically fix this in Outfit Studio right now.

It would be fixed if you assigned all the unassigned triangles to the torso segment, but I couldn't spot them visually.
