### ISSUE TITLE
Still Getting Issues with Obj Export/Import

### ISSUE THREAD

**Issue by AdamVezina** [ousnius/BodySlide-and-Outfit-Studio#203]
Same issue as Bug #8 which was closed back in 2015.
Exporting an outfit shape to obj and then re-importing back to the same shape, in the same project, even in the same session, will cause the shape to deform or explode, but not match the shape that was exported.

I remember this working long ago before Outfit Studio was split off from the Bodyslide executable and made standalone.

This only seems to affect shape imports. There are no issues with importing objs as slider data.

Version 4.7.0

**Comment by ousnius** [comment]
I need an example OBJ file and the info on what game it happens for.

**Comment by AdamVezina** [comment]
You got it.

Here's a link to the Obj and the OS files: http://www.mediafire.com/file/ysgwz79bnwb113d/Dragon_Lilly_SSE_for_Ousnius.7z/file

It's for Skyrim Special Edition.
This one doesn't explode, but the import does introduce a ton of jaggeds.

**Comment by ousnius** [comment]
Only the slider data export to OBJ saves the OBJ file without any triangles, which makes sure that the triangle array can't change the order the vertices have to be loaded from the OBJ.

The regular shape export to OBJ obviously has to keep the triangles in the OBJ, so that you can load it properly into other software while keeping that information.

Meaning, if you export a shape to OBJ and import it back, it probably won't have the same vertex order anymore and cause the artifacts you're seeing.

You can use the OBJ export/import on a slider instead.
