### ISSUE TITLE
[FO4] Certain TRI(head) files from M-Face crash the game

### ISSUE THREAD

**Issue by jobobby04** [ousnius/BodySlide-and-Outfit-Studio#213]
As you probably know from my last issue I am working with head morphs right now. You fixed the last issue and it has let make the plugin and then move onto the next step of the process, testing them ingame. Sadly it crashed right away.

I narrowed down the issue to the mod I used as a base, [M-Face.](https://www.nexusmods.com/fallout4/mods/18998) For some reason some of the tri files in that mod when exported out of bodyslide crash the game. 

I have tested the vanilla tri files of the same file, and they work fine after being in and out of bodyslide. 

Original M-Face tri files:
[Original Files.zip](https://github.com/ousnius/BodySlide-and-Outfit-Studio/files/3317497/Original.Files.zip)

Bodyslide exported ones:
[Bodyslide Tri Files.zip](https://github.com/ousnius/BodySlide-and-Outfit-Studio/files/3317498/Bodyslide.Tri.Files.zip)

I have a theory so I can workaround this issue, its moving the sliders over to the vanilla tri file. I will be trying it tomorrow.

**Comment by ousnius** [comment]
@jobobby04 Were you able to find out anything regarding this issue?

**Comment by jobobby04** [comment]
Yep, I tested moving the M-Face morphs over to the vanilla try file by exporting them as obj's and then adding them onto the vanilla tri file. I had no crashes. Here is the tri file if you want it. 
[Bodyslide Vanilla + M-Face TRI File.zip](https://github.com/ousnius/BodySlide-and-Outfit-Studio/files/3424122/Bodyslide.Vanilla.%2B.M-Face.TRI.File.zip)

I only did the one since I moved onto something else for now.

**Comment by ousnius** [comment]
The original .tri files from M-Face have something weird about them. They have exactly half as many entries for UV (texture coordinates) data as they should have.

The same .tri files in the vanilla game, in "Asian Face" and "Oni Face" don't have this issue.
Outfit Studio discards the UVs when they don't match the vertex count, which then causes a crash in the game.

Since it's only these specific .tri files, I'll close the issue for now as there's not much I can do to restore already missing data.

**Examples:**
36 vertices, but only 18 UVs instead of 36
34 vertices, but only 17 UVs instead of 34
