### ISSUE TITLE
List of Suggestions

### ISSUE THREAD

**Issue by Syer10** [ousnius/BodySlide-and-Outfit-Studio#221]
1. A group conflict editor, the idea is that you have a bodyslide group, and then you throw it into a group editor, and it shows you all conflicts that would happen if batch built, and you can remove the losers of the conflict from the group. It would also be nice for a preview function that you can use to choose the winner. This would be useful for people who create custom groups off all their outfits that they then want to remove some from the conflict list when batch building.

2. A outfit metadata/file editor, it would be nice to have a bulk editor for editing osp files, some features that would be nice are changing shapedata folder(in bulk), changing filename(also in bulk, like adding a prefix or suffix), changing outfits names, changing building location and name, changing single slider/2 slider. All of this stuff I have done a lot manually

3. An add outfit to group button, currently I am building my custom group file, and one of the things I am doing is adding outfits with custom sliders like zaps and stuff to it, and a quick add outfit to group/file would be really helpful.

**Comment by ousnius** [comment]
1. It's no "group" conflict editor, but BodySlide has since received a batch build conflict detection and selection at the bottom of the main frame.
2. See #352 
3. Use the group manager - the issue with a quick "add to group" button would be that it could pollute the group XML files, because you're choosing a group name to save to and not a specific XML file. This is a topic for a remake/redesign of the tool if such a thing happens in the future.

I'm closing this issue as the topics are partially resolved or mentioned in other issues.
