### ISSUE TITLE
Change priority of outfits in a group

### ISSUE THREAD

**Issue by PaulBGD** [ousnius/BodySlide-and-Outfit-Studio#224]
**What is it that you want to do that isn't currently possible?**
I don't believe currently there is a way to change priority on the default selected option under batch build. This is an issue when using several conflicting outfit sets, as selecting each one individually takes time when rebuilding. My current solution is having multiple groups (RunThisGroupFirst, RunThisGroupSecond, etc..) but it seems like it'd be easier if you could order the outfits in the Group Manager for each group, then have the order dictate which one is more important.

**Request the feature**
Appreciate the work, would love this feature! Would also be willing to work on it if pointers were given.

**Comment by ousnius** [comment]
@PaulBGD 
The order in a group would only do so much, since you can select multiple groups for a batch build. The simplest solution is to just not create outfit mods/groups that have the same output path in them. Those should be split up into multiple groups (like physics and non-physics).

Ordering outfits in groups would add another layer of complexion that I'm trying to avoid, but ideas are welcome.

**Comment by PaulBGD** [comment]
Yeah you're right.. I went through and manually selected options in a group, so now it's just one build.
