### ISSUE TITLE
Weight painting issues in 5.0

### ISSUE THREAD

**Issue by ousnius** [ousnius/BodySlide-and-Outfit-Studio#263]
People on the Nexus have commented on a few issues related to the 5.0 update with weight painting.

1. One person requested for a way for the new live weight normalization to be turned off (not with the state icons, but with a separate toggle)
> The downside of this is that after the last update (5.0) the bone normalization system did not go as expected. I believe that now we have totally lost the little autonomy that we still had in editing bones manually. The fixed weight bush has kind of become obsolete, when editing bones manually, it looks like an explosion of vertices out of control. I really can't edit anything manually, it's sad, there is only the automatic copy, which in my view is half the conversion process. The solution I see is the possibility of disabling the normalization of the bones in real time, otherwise the way is to use an earlier version of the program before this update.

2. There seem to be issues with the weight brush, quote: 

> Tried the 5.0 but it was placing random color for weight painting no matter what I did so had to revert. Even with the X-mirror set to off it's still placing random colors. No idea what they did but for me the weight painting changes don't seem to be working right.

> Same issue here. Already went back to the previous version. Too bad, because the new features (especially auto bone mirroring) are very useful.

**Comment by ousnius** [comment]
@sts1skj Could you take a look at these please, before I try delving into it myself?

**Comment by sts1skj** [comment]
@ousnius Do you want me to add a toggle for turning off automatic weight normalization?  (I do not consider it useful.)

Is there a way to get more information on what the problems are that people are having?  The descriptions in the bug report above aren't enough for me to understand the problem.  Phrases like "explosion of vertices out of control" and "still placing random colors" are especially opaque to me.

I've used the new weight painting system a great deal over the past few weeks, tweaking bone weights on over a dozen outfits so everything moves as well as it can without changing the topology of the meshes, and I've never encountered a bug or something that didn't work right.  I've used the fixed-weight brush a great deal, too; it's great for balancing left-right weights on the centerline with x-mirror-bone on; it's also great for making solid armor pieces not distort as the bones move.  I've never seen something that sounds like the issues mentioned.  So I could really use more information.

Do I need to pay attention to posts on the Nexus?  I don't think I've ever looked at the "Posts" tab for BodySlide and Outfit Studio on there.

**Comment by ousnius** [comment]
@sts1skj You're probably right in that it's not necessarily useful, but a lot of people are used to the way the weight painting responded before (even if it was mathematically wrong), so it should be added back as an option. Maybe a checkbox somewhere around where the "Fixed Weight" checkbox resides as well.

I haven't weight painted much the past months or after these changes, that's why I came to you first. If you're not seeing any issues yourself, then maybe the live normalization ("random colors") is what's confusing people, or maybe there's certain meshes where weight painting acts weird.

I can ask for more information or NIF files, but most of the time it doesn't lead to much. I'm certainly always looking at my comments, so you don't have to if you don't feel the need to.

The checkbox for disabling normalization might be a valid workaround for these unknowns for now.

**Comment by sts1skj** [comment]
Okay.  I'll start implementing the "Normalize weights" checkbox, unless you'd rather do it.

**Comment by ousnius** [comment]
Feel free.

**Comment by sts1skj** [comment]
I've submitted the pull request.

There are enough brush-related widgets in the "edit" pane on the right side now that I suggest moving some of them into the brush-settings pane, in a new column to the right of the sliders, since the sliders are much wider than they need to be to be practical.  I suggest moving "Fixed Weight Brush", "Normalize Weights", and "X-Mirror Bone", since those are all brush settings.  I also suggest adding an "X-Mirror" checkbox; having it only in the Edit menu is somewhat awkward.

Would you like me to write some documentation on how the automatic normalization system works?  Perhaps this bug report could have been avoided by just giving the users some documentation.  I see there's already a "Brushes and Tools" documentation page; maybe I could add details to that.

**Comment by ousnius** [comment]
Feel free to write up some documentation, but keep it simple and to the point. Most people won't get any use out off too technical, complex or large documentation about one topic.

I will merge your PR and possibly move the checkboxes tomorrow.

**Comment by sts1skj** [comment]
I looked, but I couldn't find a way of editing the wiki documentation directly.  (I'm not very good at finding things.)  The most straightforward means I could find was writing a message like this and letting you integrate the changes to the documentation yourself.  Please let me know if there's a better way.  The rest of this message is my suggested text for the weight normalization features:

### About weight normalization

In a nif file, for a skinned shape, the bone weights of a vertex must add up to 1.  In addition, for Skyrim SE and older games, at most four bones may have weights on a vertex.  In order to guarantee this, when a nif file is saved, Outfit Studio throws out all but the four highest bone weights on each vertex and then normalizes the remaining weights so that they add up to 1.

![image](https://user-images.githubusercontent.com/59774938/77596224-0a5f9080-6ec1-11ea-9a52-d764c680246a.png)
With live normalization on, instead of waiting for you to save the file before normalizing, Outfit Studio normalizes as you paint with the weight paint brush.  If you increase the weight for a bone on a vertex, weight is taken away from other bones for that vertex.  If you decrease the weight, it is added to other bones.  Adding weight to other bones that already have some weight is preferred over adding weight to bones that have zero weight.

![image](https://user-images.githubusercontent.com/59774938/77596323-53174980-6ec1-11ea-9eaa-46d0484e1f59.png)
You can control _which_ bones have weight taken away or added by toggling the "modify during normalization" flag next to the bone.  There are two main modes of operation for these flags:

- If no bones have the "modify" flag set, or the only bones with the "modify" flag set are the selected bone and the x-mirror bone, then the "modify" flags are ignored.  Weight is added or removed from any other bone during normalization.

- Otherwise, only those bones with the "modify" flag set (not including the selected bone or the x-mirror bone) will have their weights modified during normalization.  All other bones are locked.

There are two special cases worth mentioning:

- If the weights are not already normalized (which can happen for some vertices after doing "Copy Weights"), painting with the weight brush will cause Outfit Studio to attempt to normalize weights for all vertices within the brush's radius.  This can cause a sudden big change in weights.

- If just one bone has the "modify" flag set other than the selected bone and the x-mirror bone, and that modifiable bone has zero weight for the vertices you're brushing, then the selected bone can only take weight from the x-mirror bone and vice versa.  This is handy for equalizing weights on the centerline.

**Comment by ousnius** [comment]
@sts1skj I was meaning for you to do that (as a comment). I will merge it into the wiki, thank you. :)
