### ISSUE TITLE
Merge two or more meshes into one

### ISSUE THREAD

**Issue by emptyngton** [ousnius/BodySlide-and-Outfit-Studio#267]
**What is it that you want to do that isn't currently possible?**
In outfit studio, there is an option to separate vertices. Which allows users to create two separate meshes. But there is no option to merge them back.
**Request the feature**
I suggest adding the "merge vertices" option when one or more meshes selected to Outfit Studio.

**Comment by ousnius** [comment]
Unfortunately this isn't something that's possible for technical reasons. This would only be possible for meshes that use IDENTICAL textures and shaders, and those cases are very rare, so it's not worth doing it.

This task is up to 3D modeling software, so that you can adjust the UV map and more to fit the merged mesh and its textures.
