### ISSUE TITLE
Imported meshes lack global-to-skin transform needed for FO4 (in 5.0)

### ISSUE THREAD

**Issue by ousnius** [ousnius/BodySlide-and-Outfit-Studio#274]
When importing an OBJ file and copying weights to it, Outfit Studio version prior to 5.0 copied the transform of the bone to the target. 5.0 doesn't do this anymore, which is why imported meshes stay under the ground where the mesh is located instead of getting transformed to the right location.

A checkbox is needed in the Copy Bone Weights dialog that is checked by default and will restore the old behavior of setting bone transforms (or something that will result in the same).

**Comment by sts1skj** [comment]
Here's my explanation from the previous discussion:

Here's my analysis of the problem (with no attempt to suggest a fix yet).  I don't have FO4, so the only sample files I have are the ones you've sent me.  The file 'FO4 CBBEBody.nif' (which you sent me for transform testing) has a single shape with a non-identity global-to-skin transform: translation=(.0002,.8818,-120.844), no rotation or scale.  In the FO4 nif format, this transform is not stated explicitly in the file and is instead implied by the skin-to-bone transforms.  When we use OS (4.9.0 or 5.0.3) to export this nif to obj, no transform is applied (except a fixed scaling by 0.1), so the exported data are in the shape's skin coordinates, not global coordinates.  In OS 4.9.0, the global-to-skin transform is not recorded internally; it is implicitly set when the skin-to-bone transforms are copied during the bone weight copy (in CopyBoneWeights, FO4-specific block), implicitly copying the global-to-skin transform as well for bones added in the copy process (which means you can easily get a mismatch, with different bones using different global-to-skin transforms; bad).  In OS 5.0.3, the global-to-skin transform is recorded explicitly (in AnimSkin::xformGlobalToSkin).  For FO4, this transform is calculated when the nif file is read (in AnimSkin::LoadFromNif).  The skin-to-bone transforms are calculated as needed from the bone-to-global transforms and the global-to-skin transform, ensuring that the implied global-to-skin transform is the same for all skin-to-bone transforms (which is good since the points are represented in just one skin CS).  When a shape is exported to OBJ, no transform is applied (except scaling by 0.1), so the points are in skin CS, offset from global CS.  When a shape is imported from OBJ, the global-to-skin transform is not set, leaving it the identity transform, which means OS 5.0.3 assumes that skin CS is the same as global CS for imported OBJs.

Here are the ideas from the previous discussion:

Idea 1: transform coordinates to global CS on OBJ export, possibly as a user-controlled option.

Idea 2: let user edit shape's global-to-skin transform.

Idea 3: ask user if they'd like to copy the global-to-skin transform when doing a bone weight copy and the target has no bone weights.

Idea 4: set global-to-skin transform on OBJ import for FO4 to some fixed transform.

Idea 5: give user option to transform all geometry in a shape so that the skin CS is the same as the global CS.

ousnius approved 1, 2, and 3, with 3 to be done first.

**Comment by ousnius** [comment]
Fixed with 05f695c
