### ISSUE TITLE
Helper nodes getting removed

### ISSUE THREAD

**Issue by ousnius** [ousnius/BodySlide-and-Outfit-Studio#280]
After 5.0.x, child nodes without weights are getting cleaned up as well. However there are certain HDT PE NIFs that make use of helper nodes (without weights) to control certain physics/constraint properties.

These are now getting removed. They can be copied back using NifSkope, but it looks like we need a way to keep these: either a checkbox you tick before saving/export, or we have to keep custom bones even if they have no weights.

**Comment by ndaley7** [comment]
Hey thats me!
As referenced by Ousnius, current workaround is to copy the helper nodes in nifskope:

CTRL+C in the source NIF (center 1)
CTRL+V on NPC Pelvis in target NIF

**Comment by sts1skj** [comment]
I recommend removing the call of DeleteUnreferencedNodes in AnimInfo::WriteToNif added in commit c8fa69f.

**Comment by ousnius** [comment]
@sts1skj What would be the alternative? Turning it into a manual action only, similar to Remove Skinning?

I think I would prefer if it simply didn't remove custom nodes, but then DeleteUnreferencedNodes would need logic for which nodes those are...

**Comment by sts1skj** [comment]
Making it a manual action only, similar to Remove Skinning, would be safe.  But when would it be desirable to use the "Delete Unreferenced Nodes" command?

As for making DeleteUnreferencedNodes only delete non-custom (or standard) bones, this would require external information, since that function is in lib/Nif, which isn't supposed to know anything about the reference skeleton.  Looking for bones in the reference skeleton is how the rest of OS determines whether a bone is standard or custom.

But I'm not sure restricting it to only delete standard bones is enough.  I can imagine that a mod might make use of unreferenced standard bones as well as custom bones.
