### ISSUE TITLE
Feature request: Subdivide Meshes

### ISSUE THREAD

**Issue by galvinhoang** [ousnius/BodySlide-and-Outfit-Studio#292]
When trying to increase the vertex count in order to make the mesh count more detailed, you could either use the "Split Mesh Edge"-Tool or use another program like blender. However with the "Split Mesh Edge"-Tool, you would hat to manually select every mesh edge one by one and when using other programs like blender, a lot of information of the .nif file gets lost when exporting/importing the file (to another format and back) and it takes quite a lot of time (after importing a file, I would again have to redo the entirety of body sliders, add segments etc...).

As the "technology" to subdivide a single Mesh edge one by one is already there, a feature would be great, to automatically split all of the (unmasked) mesh edges without being required to do it one by one (similar to the subdivide function in Blender).

**Comment by GreenGhost21** [comment]
I'd like to see this as well, actually. It would certainly save the trouble of exporting outfits to FBX (which is currently broken, as far as I can tell), subdividing the resulting meshes in another program, and importing the new meshes. Splitting the edges one-by-one is not only inefficient, but in my experience, it keeps the subdivisions from being regular, and results in a bit of a mess of polygons. 

P.S. I apologize if I'm not supposed to reply to this kind of thing, but I can't figure out any other way of expressing my support for this request.

**Comment by sts1skj** [comment]
When I first created the split-edge tool in April 2020, I thought the idea of splitting all the unmasked edges in a mesh was not useful.  Since then, however, I've found myself wanting such a tool again and again.  So I now agree: this would be a useful command in Outfit Studio.

The existing split-edge tool has to create a lot of new data:
- The coordinates of the new vertex (very complicated circle fitter)
- Two or four new triangles to replace one or two old triangles
- UV, color, eyedata, tangent, bitangent, bone weights (easy: average the two endpoints)
- All of the vertex-position slider diffs (more circle fitting)
- All of the UV slider diffs (easy: more averaging of the two endpoints)

The new split-all-unmasked-edges algorithm would need to calculate all of this for all the new vertices.  For most of the above data, it can (and should) be calculated simultaneously, using only information already present.  That should work well for everything above except the triangles.  Updating the triangles can't be done simultaneously; they have to be done in some order.  Different orders will give different triangulations.

Option 1: pick an arbitrary ordering of the vertices in which to update the triangles.  This would be easy to do, but the resulting mesh would likely have a huge number of edges that would have to be manually flipped with the flip-edge tool.

Option 2: update triangles for longer edges before shorter edges (so the edge list would be sorted by length for the purpose of triangle changes).  I'm not sure how well this would work, but it might produce excellent results.

Option 3: write a (possibly separately invoked) algorithm for flipping lots of edges to try to obtain some nicer result.  But what should the heuristic be?

What parameters should the split-all-unmasked-edges algorithm have?  Should there be a minimum edge length such that edges shorter than that length are not split?  Should there be a maximum number of new vertices, with longer edges having priority?  Maybe, instead of splitting every edge, only enough edges should be split so that each triangle is split in two?

Ideas?  Suggestions?  Opinions?

**Comment by sts1skj** [comment]
Since no one had any suggestions, I decided to go with option 2.  It seems to work okay.  I chose to not implement any parameters; the command splits every edge between two unmasked vertices.

It would be really nice if we could mask edges instead of only vertices.  If someone ever implements edge-masks as an alternative to vertex-masks in Outfit Studio, the Refine Mesh command should be updated to use edge masks.
