### ISSUE TITLE
FBX import not working correctly since 5.0.4

### ISSUE THREAD

**Issue by capmac** [ousnius/BodySlide-and-Outfit-Studio#293]
**Description**
Since 5.0.4 FBX file imports behave differently. Imported models are placed below the reference body (z axis), instead of on the body. Roughly around -120 on the z axis.

**How to reproduce**
Import an existing FBX file applying a body armature to a model and compare version 5.0.3 with 5.0.4.

**Comment by ousnius** [comment]
@capmac For which game? Can you attach an example FBX file please?

**Comment by capmac** [comment]
Fallout 4

[Gloves.fbx.gz](https://github.com/ousnius/BodySlide-and-Outfit-Studio/files/4651844/Gloves.fbx.gz)

**Comment by sts1skj** [comment]
@capmac Here's a temporary workaround for the problem: after importing the fbx file, open the Shape Properties dialog, go to the Coordinates tab, enter 0.881800 in Origin-Y and -120.843712 in Origin-Z, uncheck "Recalculate Geometry", and hit okay.  Repeat for each shape.

(The skin coordinate system isn't being set properly on fbx import.  These are the typical values for Fallout 4.)

**Comment by sts1skj** [comment]
@ousnius This is a continuation of issue 274.  We didn't do idea 4 from that issue.  Maybe we should?

**Comment by sts1skj** [comment]
@capmac Here's another workaround: when you do "Copy Bone Weights" on a shape imported from FBX, there's a checkbox called "Copy skin transform from reference".  Make sure it's checked; it sets the skin coordinate system, just as if you'd done it in the Coordinates tab of the Shape Properties window (as I suggested in my previous comment).  Make sure the checkbox "Recalculate geometry's coordinates so it doesn't move" is _not_ checked.

**Comment by sts1skj** [comment]
@ousnius Idea 4 from issue 274 was:

Idea 4: set global-to-skin transform on OBJ import for FO4 to some fixed transform.

We didn't implement idea 4 (neither for OBJ nor FBX).

Also relevant is idea 1:

Idea 1: transform coordinates to global CS on OBJ export as a user-controlled option.

We did implement idea 1, but only for OBJ, not FBX.

**Comment by capmac** [comment]
Thanks @sts1skj 
Setting the coordinates  does the trick. And also fixes the problem I had when exporting gloves to Nif afterwards, It did not export the finger bones or weights correctly before I believe.
But it's a pain to do for every imported shape. Better to do this in an automated way as it did before.

Copying weights I did not try. But that would overwrite the weights from the imported fbx file with those of the reference model, would it not? 
I prefer doing weight painting in a tool like Blender.

**Comment by sts1skj** [comment]
@capmac Yes, copy-weights would overwrite the weights from the imported fbx file.

@ousnius As far as I can tell, neither the global-to-skin transform nor any of the skin-to-bone transforms are exported to the FBX file.  So the FBX file does not have any information about the skin coordinate system (except, of course, that all the geometry is offset from where it should be).  Please let me know if this isn't correct.

**Comment by ousnius** [comment]
@sts1skj Afaik it simply puts the vertices and root + nodes (GetTransformToParent) in, yes.

**Comment by sts1skj** [comment]
As I see it, the basic problem here is this: how to set the global-to-skin transform on OBJ/FBX import.

Ideally, this transform would be saved in the OBJ/FBX file, so we could just load it with everything else.  But it's not.

It would be great if the geometry in OBJ/FBX files was represented in global coordinates instead of skin coordinates.  Then we could just set the skin coordinate system to be the same as the global coordinate system.  Unfortunately, geometry in OBJ/FBX is currently represented in skin coordinates, not global coordinates (though we now have the option on OBJ export to use global instead of skin).

Before I started messing up the transform code, Outfit Studio effectively copied the global-to-skin transform from the reference shape, if there was one.  (It only did this for FBX, not OBJ.  The code was in OutfitProject::ImportFBX, in the block "if (baseShape)".)

It would be fairly easy to add code to copy the global-to-skin transform from the reference shape, if there is one.  But I would expect that there wouldn't be a reference shape 99% of the time.  And this would only work if the reference shape had the correct transform for the shapes being imported.

One messy idea is to set the global-to-skin transform on OBJ/FBX import to a fixed value that depends on the current game.  If the current game is FO4/FO4VR, it could be set so that the global-to-skin offset is (0,.8818,-120.843712).  This would work for the Gloves.fbx file given earlier in this thread.  Unfortunately, the typical offset depends on the skeleton: for Fallout 4 power armor (such as ExoSkeleton_Frame.nif), the typical offset appears to be (0,0,0), not (0,.8818,-120.843712).

And, of course, there's always the possibility of asking the user to decide what to do.

**Comment by sts1skj** [comment]
It might also be possible to automatically guess whether an offset is needed.

With a reference shape, we could check whether the new shapes line up better with the reference if we copy the transform versus if we don't.

Without a reference shape, we could check if all the z coordinates are negative.

**Comment by sts1skj** [comment]
Here's my proposed solution:

Piece 1: When exporting an FBX file, ask the user if they'd like to transform the geometry to global coordinates, with a warning that this is not recommended, just like it currently does for OBJ.

Piece 2: When importing an FBX file, if there's already a reference shape, and the reference shape has a non-identity global-to-skin transform, ask the user if they'd like that transform copied to the shapes being imported.

Optional piece 3: When displaying the question for piece 2, calculate whether the imported shapes will line up better with the reference shape if the transform is copied or not, and give the user a recommendation.

Optional piece 4: When importing an FBX file, and there's no reference shape, and the current game is Fallout 4, and the z coordinates are negative, ask the user if they'd like the global-to-skin transform set to the typical non-identity transform.

@ousnius Do you approve this plan?  Shall I get started?  Do you want either of pieces 3 or 4?

**Comment by ousnius** [comment]
@sts1skj 
1 and 2 make sense, I don't think we need 3 for now.

4 is probably important as well, as I can imagine a lot of the time people import the FBX first.
However I'd like to not have that one in for now as it requires hard coding a transform. We can show a warning message instead that always shows when loading an FBX without anything else (or a reference) loaded. Older versions of OS did something along those lines for FBX import already.

The message after choosing an FBX file could be something along the lines of:
"For correct bone transforms, you might need to load a reference before importing FBX files. Import anyway?"

Feel free to implement 1 2 and my suggestion for 4.

**Comment by sts1skj** [comment]
I apologize for taking so long to get this done.  I let myself get distracted with other projects.
