### ISSUE TITLE
"Smooth an area of a mesh" brush causes mesh tearing.

### ISSUE THREAD

**Issue by emptyngton** [ousnius/BodySlide-and-Outfit-Studio#298]
**Description**
Bug reproducible only in OutfitStudio version 5.0.7. There is no such issue in the previous version.
Game: Skyrim LE
Outfit Studio x64 5.0.7

**How to reproduce**
1.  Import NIF from the archive
2. Select Smooth an area of a mesh with 100% strength parameter
3.  Use the brush on the mesh and observe tearing in certain areas (Usually it is the area where UV seam laid)

[bodymesh.zip](https://github.com/ousnius/BodySlide-and-Outfit-Studio/files/4883737/bodymesh.zip)
![SNAG-0001](https://user-images.githubusercontent.com/40150265/86755221-78af0580-c00f-11ea-9e22-a93d12e3754a.jpg)
![SNAG-0002](https://user-images.githubusercontent.com/40150265/86755223-78af0580-c00f-11ea-92f0-3bda588cc307.jpg)

**Comment by ousnius** [comment]
@sts1skj Do you think you can take a peek at the issue and if it needs to be or can be fixed/improved, please?

**Comment by sts1skj** [comment]
@lapiroman It would be really helpful if you could give us a specific nif that demonstrates the problem, whether by name or by attaching the file here.

@ousnius Looking at the diff between 5.0.6 and 5.0.7, it seems likely that the problem is being caused by the changes to kd_matcher and SortingMatcher, since these functions determine whether points are welded.  One possibility is that there's a subtle bug in SortingMatcher.  But another strong possibility is that the mesh that demonstrates the problem has points that are borderline too far apart to be welded; kd_matcher and SortingMatcher have some arbitrariness for such points.  I would like to test for myself to see.

**Comment by emptyngton** [comment]
@sts1skj Please check bodymesh.zip attachment above screenshots it contains .nif file to reproduce that issue.

**Comment by sts1skj** [comment]
Pull request 300 fixes the specific problem where the smoothing brush opens a seam at the given spot on the given mesh.  As I essentially rewrote the point matcher from scratch, it's entirely possible that the new algorithm has other bugs.  But I didn't see any in some quick tests.
