### ISSUE TITLE
Feature Request: Merge vertices together

### ISSUE THREAD

**Issue by ghost** [ousnius/BodySlide-and-Outfit-Studio#302]
Opposite to how you can split an edge and create a vertex, how about being able to merge 2 vertices together? This would be a huge help especially for outfits that have loose vertices and open holes because the author didn't merge them in Blender beforehand and having the option to merge vertices in Outfit Studio makes it so we don't have to go to Blender and re-export a nif. It'd be a major quality of life improvement imo and lets you fix various mistakes on a model if possible.

**Comment by ousnius** [comment]
@sts1skj How difficult do you think a tool for this would be, now that we have the flip, split and delete tools?

**Comment by sts1skj** [comment]
@MrManMain It's unclear to me what capability you're asking for that you can't do with the collapse-vertex tool.  Combined with the flip-edge tool, the collapse-vertex tool lets you close holes and eliminate almost any vertex.  Could you give a detailed example or two or three?

@ousnius At one point, I asked if you'd like me to write some documentation giving examples of doing complex tasks using the simple mesh-editing tools.  One of the examples considered was "closing a one-triangle hole".  You declined to have me write that documentation.  Would you like me to write some of that example documentation?  Here's the list I suggested (in a Discord conversation on April 16th):
- how to collapse a vertex with more than three connections.
- how to close a one-triangle hole.
- how to create a one-triangle hole.
- regularizing a mesh to remove texture distortion.
- cutting out a lattice.
- refining a coarse, low-polygon region.
- restoring a small accidentally-deleted portion of a surface.
- smoothing a surface by shortening edges with edge-flipping.

I'm not certain that any such documentation would be relevant to MrManMain's request, but it might.

**Comment by ousnius** [comment]
@sts1skj Feel free to write the documentation, people do seem to be hesitant on trying out the tools. But I guess it's normal for the more complex ones. I can put it on its own wiki page. You can send the markdown or text to me in a DM.

**Comment by sts1skj** [comment]
@ousnius What do you mean by a DM?  I don't know how to send a direct message on github.

**Comment by ousnius** [comment]
> @ousnius What do you mean by a DM? I don't know how to send a direct message on github.

Discord

**Comment by ousnius** [comment]
@MrManMain https://github.com/ousnius/BodySlide-and-Outfit-Studio/wiki/Mesh-Editing-Examples-(intermediate-and-advanced) Does this help?

**Comment by ghost** [comment]
Sorry it took so long to answer.

@sts1skj Sorry, I'll try and clarify and if it still sounds complicated, try to read into what I'm saying at face value. 
![bild](https://user-images.githubusercontent.com/43208856/88427022-76f88680-cdf2-11ea-9ce7-8a0672fc76fd.png)

So on this part of the outfit with the plate and chainmail, as you can see the vertices are not connected. The idea I have is that through pressing a key combination on your keyboard or a button on the toolbar of Outfit Studio, it would put you in a mode where you can select a certain number of vertices (like 2) and then give you the option turn those vertices into 1, thus they become merged. This would then become a manual process for any other parts of the mesh like the one you just fixed by merging 2 vertices into 1 (since there are, for example, multiple parts of that whole that are separate and not just 2 vertices and so you gotta merge them manually)

If you have a better idea for this though I'm happy to listen to it. And I hope this explanation is better. I don't know how else to phrase it.

@ousnius Not particularly, no. It's similar but it's not the same and the process is not as easy as the push of a button like in a more standard 3d software like Blender or Maya.

**Comment by sts1skj** [comment]
@MrManMain In your example, there are two possible cases that I can see: the vertices have the same UV coordinates or different UV coordinates.  (Roughly, the texture matches across the gap or doesn't.)

If the UV coordinates do match across the gap, then you truly want to merge the vertices, as you say, thus reducing the total number of vertices.  You can do that in Outfit Studio now, crudely, by following the procedure for closing a hole in a surface: eliminate (collapse) the boundary vertices one by one until there are only two left, at which point the hole is closed.  Of course, along the way you're losing a lot of vertices, and you have to add them back in again and position them (in both space coordinates and UV coordinates) in order to make the surface look more or less how it did before.  So this is a crude solution, but it is possible in the current Outfit Studio.  If you want me to create an example of this procedure, please attach a file.

If the UV coordinates do not match across the gap, then you do _not_ want to merge them: you want to weld them.  When two vertices are welded together, they have the same space coordinates but different UV coordinates.  Nearly every outfit has examples of welded vertices; you can detect them by seeing that the vertex number displayed in Outfit Studio's status bar changes as you move the mouse around the vertex.  In order to weld two vertices in Outfit Studio, you need to force them to have the exact same space coordinates.  To edit a vertex's space coordinates in Outfit Studio, hit the 'V' key on your keyboard.  So, to weld vertex A and vertex B, move the mouse over vertex A (with the move brush selected), make note of A's coordinates in the status bar, then move the mouse over vertex B, hit 'V', and enter A's coordinates.

@ousnius As the above procedures are somewhat painful, it might be nice if there were a tool in Outfit Studio to weld and/or merge two vertices.  In such a tool, the user would somehow select two vertices and command them welded.  As Outfit Studio currently doesn't have a way of selecting vertices, this could be a mess to implement.  At the moment, I have three ideas:

1. One way would be to implement a vertex-selection tool.  Then a command could be issued to weld or merge all selected vertices.  The command could be easy to implement; but writing a selection tool sounds challenging to me.

2. A similar but easier-to-implement way would be to use the existing mask brush as a sort of selection tool.  The user would mask all vertices but the two to be merged or welded, and then issue a command to merge or weld the unmasked vertices.

3. Another way to do this would be to create a tool that automatically figures out which second vertex to weld the vertex under the mouse to.  The second vertex could be automatically selected by just finding the closest non-welded vertex in the mesh.  This tool would probably be quicker and easier to use, since in most cases the user would just have to click on a vertex and it would be merged or welded with the nearest vertex that made sense.  If the vertices were too far away from each other, the user could move one of them before attempting to merge/weld.

Probably there are other good ways of doing this; these are just the three options that came to mind now.

**Comment by sts1skj** [comment]
@ousnius Perhaps it would be best if "merge vertices" and "weld vertices" were two separate commands or tools.  In most cases, you could automatically determine which to pick: if the UV coordinates are the same, you merge; if they're far apart, you weld.  But I can imagine cases where the UV coordinates are close but not identical; in that case, it would probably be best for the user to decide whether to merge or weld.  Because of that, maybe they should just be separate commands or tools.  I don't know.

**Comment by sts1skj** [comment]
@ousnius Perhaps better than having separate merge-vertices and weld-vertices tools would be to have a single "weld and then merge" tool.  If the user clicks on vertex A, and the closest other vertex is vertex B, if they're not welded, it welds A to B; if they are welded, it merges A into B.

**Comment by ousnius** [comment]
@sts1skj I'm still not sure on how far Outfit Studio should go in terms of mesh editing, because at some point it is always more efficient to go to Blender or Max and use their full feature-set instead. Personally I probably won't be trying to implement weld/merge, but feel free to open any PRs at any point.

A user may want to merge "a welded vertex" (which really consist of two) and one beneath, which would mean actually merging 3 vertices into one. Maybe it can be one tool, but the program should ask if the two vertices that are currently virtually welded should be welded for real. If one declines, nothing happens and you can't merge the virtually welded ones with others before you weld them for real.

**Comment by rcodegrove** [comment]
+1 for some very basic functions here.  I have been trying to weld vertices that have separated due to overdoing smoothing and using 'V' and coordinates for correcting errors which does the job. But there seems to be bugs when sliders are active, which is usually when it is needed.  The coordinate's seem to jump to random values.  I am trying to diagnose the specific conditions.

I originally made a comment that stated the X axis specifically showed random behavior but then retracted it when it appeared to not be the only one.  It does now appear to be consistently wrong when sliders are active and have positive values.  Opening the V dialog and pressing Ok without altering any values causes X to randomly change, but Y and Z to remain stable as expected.   I think there are conditions that all axis can be problematic though.

**Comment by sts1skj** [comment]
There are some additional ideas on this request in request #380 .

**Comment by sts1skj** [comment]
@MrManMain @rcodegrove Pull request #419 implements a new move-vertex tool that has options for weld and merge.  Is this sufficient to satisfy your feature request?

I apologize for taking so long to implement this (18 months).
