### ISSUE TITLE
Coordinates bug

### ISSUE THREAD

**Issue by Indarello** [ousnius/BodySlide-and-Outfit-Studio#303]
I have bug or problem with coordinates
(video) when I change coordinates and return coordinates back, one of models fix its position, that it have before saving
(photo) I cant fix position this way on this project, it was saved before update to latest Outfit studio, in nifskope all looks good, in Outfit studio body moved and don't collide with hands and other parts
https://mega.nz/file/O3BTlIYC#GvaHXKtPOpH45aRXqjtzhriTORn040IS_k3lfSMfVdk

**Comment by ousnius** [comment]
@Indarello It's possible there's a precision loss when applying the transform (so the mesh vertices don't move as the checkbox says). What exactly is it that you are trying to do with the mesh? If it's for FO4, then the offset is intended as all FO4 skinned meshes (vertices) are located under the ground.

**Comment by Indarello** [comment]
> @Indarello It's possible there's a precision loss when applying the transform (so the mesh vertices don't move as the checkbox says). What exactly is it that you are trying to do with the mesh? If it's for FO4, then the offset is intended as all FO4 skinned meshes (vertices) are located under the ground.

This is FO4, I thought this is outfit studio bug? I just save random project and then load it and this bug happen some times
What I can do? I can send you projects

**Comment by ousnius** [comment]
@Indarello Does the bug happen when you simply do "Load Project" and "Save Project" or does it only happen when you enter the "Shape Properties" dialog and click OK? Yes, please upload a sample project. The .nif file is probably enough.

**Comment by Indarello** [comment]
Only when I load project
Also one time I was working with project, save it but dont close and open it again in a new window, and bug appeared, but in old window there was no bug

**Comment by Indarello** [comment]
> @Indarello Does the bug happen when you simply do "Load Project" and "Save Project" or does it only happen when you enter the "Shape Properties" dialog and click OK? Yes, please upload a sample project. The .nif file is probably enough.

https://mega.nz/file/m3YQVCBS#ECo-GL9J4gBmWaauGo4ePFwe5TEPTbHgegpIeGIb0v8

**Comment by Indarello** [comment]
Bug only occur in Outfit studio, not in nifskope when I just watch .nif

**Comment by ousnius** [comment]
@Indarello When you change the coordinates, it will apply them with a slight precision loss. As long as you don't change any coordinate value and click OK, there won't be any offsets caused by Outfit Studio or BodySlide.

**Comment by Indarello** [comment]
You mean there is no bug? Why I never had this problem before?

**Comment by ousnius** [comment]
@Indarello I'm not saying there's no bug, I'm just wondering why you are changing the coordinates at all like you do in the attached video.

**Comment by Indarello** [comment]
See the gap between the eye and the face?
Gap disappears (face moves a bit) if I do this

**Comment by sts1skj** [comment]
@Indarello This problem (unaligned shapes) is the result of accumulated roundoff error in the rendering pipeline.  Some of that roundoff error is already present in your nif file, but most of it is happening inside Outfit Studio.  Outfit Studio's rendering pipeline is more complicated than the rendering pipelines in NifSkope or the game.  It's especially complicated for FO4 nif files, because these files lack an important piece of information: the global-to-skin transform for each shape.  Because of the way rendering and editing works in Outfit Studio, it needs this transform, and so, for FO4 nif files, it calculates it from other information in the nif file.

In your case, the calculated global-to-skin transforms for your two shapes are different.  The differences are small, but they're big enough that the two shapes don't quite line up when rendered in Outfit Studio.  You can see some of the differences between the transforms in Outfit Studio's shape properties coordinates tab, which shows you (and allows you to edit) the global-to-skin transform.  Unfortunately, you can't see all of the tiny differences, because currently the machine-format numbers are converted to text with only six digits of precision after the decimal place.  In particular, the rotation vectors display as zero, when they're actually not zero.  The translations (or origins) are not identical either, which you can clearly see.

At some point, we're probably going to tweak the way Outfit Studio calculates the global-to-skin transform so that it has less roundoff error.  In the meantime, there's a straightforward workaround for this problem (that you've mostly discovered).  After loading your FO4 nif file into Outfit Studio, go to the shape properties coordinates tabs for every shape in the project, and set the global-to-skin transform for every shape to be exactly the same as each other.  Make sure the checkbox "Recalculate geometry's coordinates so it doesn't move" is _not_ checked, as we only want to change the transforms to be identical without also subjecting every vertex's coordinates to a small change that will introduce additional roundoff error.  With all the global-to-skin transforms for the shapes in the project identical, any remaining visual misalignment will be because of differences in the vertex coordinates, not the transforms.  Unfortunately, since the global-to-skin transform is not saved in the FO4 nif file, you will have to redo these steps every time you reload the file.

Unfortunately, we may not be able to eliminate this problem completely.  Part of the problem is that all of the data in a nif file is stored in 32-bit floating point format, which doesn't really have enough bits of precision for the task.  Ideally, critical nif data such as the transforms would be stored in 64-bit floating point, but we have no control over the file format.  Another part of the problem is that the FO4 nif file format doesn't include the very important global-to-skin transform for each shape.  We have no control over that either.  But we can definitely make changes to Outfit Studio to reduce the problem, by trying to minimize how much additional roundoff error is introduced.
