### ISSUE TITLE
OutfitStudio - Undiff multiple sliders

### ISSUE THREAD

**Issue by Yankshuru** [ousnius/BodySlide-and-Outfit-Studio#313]
**Undiff multiple sliders**

**I would like to suggest multiple-sliders edit to apply Undiff. Sometimes, all lower body sliders causes long sleeves (like oriental clothes) morphs, resulting in distortion, as solution, Undiff is necessary. I'm suggesting this because of high quantity of sliders that must Undiff to fix the problem, so a massive edit would be awesome!**

**I have to apologize in advance if this already possible, but I couldn't find anything about, I'm relatively new to skyrim edits**

![image](https://user-images.githubusercontent.com/10253991/93141080-ef284d80-f6b9-11ea-887f-9ea4e7bd7645.png)

**Comment by ousnius** [comment]
@Yankshuru Late response, but: Since only one slider can be in edit mode, the undiff brush can only be used on one slider at a time. Changing that wouldn't be a quick fix.

As a workaround you can apply a mask to the mesh for the vertices you want slider diffs to be removed from. Then invert the mask and use "Slider -> Clear Slider Data". You can smooth the mask by holding the shift key as well.

The sliders with checkboxes checked will be undiffed that way.
