### ISSUE TITLE
[NIF] Getting stuck in OptimizeFor (probably PrettySortBlocks)

### ISSUE THREAD

**Issue by Guekka** [ousnius/BodySlide-and-Outfit-Studio#316]
**Description**
When running OptimizeFor on [this mesh](https://github.com/ousnius/BodySlide-and-Outfit-Studio/files/5321305/in.zip),  the code never exits the function
From what I found, it is stuck in ``PrettySortBlocks``, and more precisely ``SortGraph``. This is probably some kind of infinite recursion

**How to reproduce**
```cpp
int main() {
    NifFile nif;
    nif.Load("in.nif");

    OptOptions optOptions;

    optOptions.targetVersion = nif.GetHeader().GetVersion();
    optOptions.targetVersion.SetFile(NiFileVersion::V20_2_0_7);
    optOptions.targetVersion.SetUser(12);
    optOptions.targetVersion.SetStream(100);

    nif.OptimizeFor(optOptions);
    nif.Save("out.nif");

    return 0;
}
```

**Side question**
NIF Optimizer handles this case just fine. Would it be possible to see the source code?

**Comment by ousnius** [comment]
@Guekka NIF Optimizer doesn't have other code - the code that's private is merely UI.

I tried the NIF and there's no infinite recursion or bug, it load and saves out fine (with or without running OptimizeFor, the NIF is already in the target version anyway). However it takes quite a bit of time even in a release build and a whole lot more (feels like infinite but it's not) in a debug build due to how many blocks and children there are in the NIF file.

So it's simply a matter of the deep structure causing it to run slowly.

**Comment by Guekka** [comment]
I don't get it. I was able to reproduce it several times (several minutes waiting and still not working). And now it works. 
Sorry for bothering you again. 
That said, it is not in my current plans, but if I made a performance PR, would you accept it? I've seen some places that could probably be made faster

**Comment by ousnius** [comment]
@Guekka This is now about 200000% faster (accurate approximation). :P
