### ISSUE TITLE
Misleading help text for unselect/mask tool

### ISSUE THREAD

**Issue by Spawnkiller** [ousnius/BodySlide-and-Outfit-Studio#333]
Description

Some small help text bug that is present since v4.1.9 (probably since the tool was introduced…):
Masking-tool (Pencil) mouse over help text description “bug”.
It tells about to hold CTRL to unselect/mask a vertex -> but this is done by hold ALT, hold CTRL does nothing when masking.

How to reproduce
Move mouse to hover over pencil tool, wait for help text to appear.

Proposal to further clarify its function:
"Click on a vertex to select/unmask it.
Hold down ALT and click on a vertex to unselect/mask it."

![image](https://user-images.githubusercontent.com/36749353/105099011-3fba1800-5aab-11eb-8014-28bfbfe5b19a.png)

**Comment by ousnius** [comment]
@Spawnkiller The text is correct, but the functionality is probably too confusing.

These two apply when you do NOT have any brush selected, so you are in selection/picking mode (shortkey key: '0'):
- Clicking on a vertex in the vertex selection mode selects it (which is equivalent to unmasking it, since something is selected when it's not masked).
- Holding down CTRL while clicking on a vertex in vertex selection mode unselects it (which is equivalent to masking it, since something is not selected when it's masked).

These two apply when you have any brush active:
- Holding down CTRL while brushing with any brush active masks vertices.
- Holding down ALT while brushing with the inflate/deflate brushes active inverts the action, so inflate becomes deflate and the other way around.
- Holding down ALT while brushing with the mask brush active removes the mask instead of adding it.

You might have confused the ALT behavior of the mask brush with the vertex picking.
