### ISSUE TITLE
Section of weight paint will not update.

### ISSUE THREAD

**Issue by SpannerLM** [ousnius/BodySlide-and-Outfit-Studio#335]
Hello. I am relatively new to this so excuse me if this isn't actually a bug, and rather just my misuse.

I've been working on creating a set of armor, and have all of the weights painted near perfect, except for two portions of what I believe are on the pelvis bone. There is a big red blotch of weight paint. Everything seems normal when I correct it, however when I export the file, that big red blotch reapplies itself. I have Normalization unchecked when I try to correct it, because when I try to correct it with Normalization turned on, well, see the video linked at the bottom.

This issue only arose when I copied the pelvis bone weight of a preexisting armor to the one I'm currently working on. Did not happen when I had originally painted it all by hand. Again, excuse me if this is actually just misuse and not actually a bug. I just didn't know where else to turn about this issue as I cannot seem to fix it. Images below:
![110fac4b55f512182efbe89a86252aac](https://user-images.githubusercontent.com/78815864/107406369-5cf46c00-6ad6-11eb-8ba7-7535fe2b00ae.png)
![bb84a383553e9cc6464e2d2adf3b8e16](https://user-images.githubusercontent.com/78815864/107406471-785f7700-6ad6-11eb-9644-129cd078bf4c.png)

[https://www.gyazo.com/37d12a80433fe625c91a9745e149c339](url) <--- Video

**Comment by ousnius** [comment]
On export, weights (up to 4 bones per vertex) will be normalized to result in a sum of 1.0 (red). You're seeing this exact effect when turning on weight normalization for the brush.

Since only the pelvis bone is affecting that area of vertices, it will always become red. The area shown looks more like it should belong (more) to one or multiple of the spine bones.

You should turn on normalization and paint additional weights for the spine bones instead of trying to remove something that can't be removed. After that, you can hold shift to smooth the weights between the bones further.

See https://github.com/ousnius/BodySlide-and-Outfit-Studio/wiki/Weight-Normalization

**Comment by SpannerLM** [comment]
Well that seemed to solve my problem real nice. I didn't know about that.
Thanks a lot! Problem solved.
