### ISSUE TITLE
additional hotkeys, mute 'done!' jingle

### ISSUE THREAD

**Issue by Morwo01** [ousnius/BodySlide-and-Outfit-Studio#383]
**What is it that you want to do that isn't currently possible?**
... Setting hotkeys, additional hotkeys in Bodyslide, muting 'Done!' jingle sound notification

**Request the feature**
... having additional hotkeys would be good for faster execute functions in Bodyslide, ie:
Outfit/Body Dropdown menu selecting next entry up in list
Outfit/Body Dropdown menu selecting next entry down in list
Preset Dropdown menu selecting next entry up
Preset Dropdown menu selecting next entry down
Save Preset
Save as Preset
Open current Outfit/Body in Outfit Studio
Groupmanager button
Scroll up slider list
Scroll down slider list
Create (outfit)
as well es edit and bind hotkeys listed above in Settings

muting 'Done!' jingle sound option - being called, (since a default windows sound)

**Comment by ousnius** [comment]
@Morwo01 I've added several hotkeys so BodySlide. Every one in your list except for "Build", unfortunately I couldn't add that one due to the CTRL modifier already being used there.

F5 = refresh outfit list from disk
PgUp = go to previous preset
PgDown = go to next preset

Ctrl+A = clear search filters
Ctrl+PgUp = go to previous outfit
Ctrl+PgDown = go to next outfit
Ctrl+O = open project in Outfit Studio
Ctrl+S = save changes to preset
Ctrl+Alt+S = save new preset
Ctrl+G = open group manager
Ctrl+P = open preview

Muting the message box sound isn't (easily) possible in the UI framework, plus I think it's kind of useful to know when a batch build is finished. You can always mute the sound in your Windows settings.

Being able to edit hotkeys isn't planned right now as it quickly becomes rather complicated. Both to assign hotkeys but also to handle them correctly.
