### ISSUE TITLE
Produced outfit causes crash in game(AE)

### ISSUE THREAD

**Issue by JunktownJerkyVendor** [ousnius/BodySlide-and-Outfit-Studio#448]
I made a bodyslide for the light refracting glass(converted with CAO), I only features I used was bone weights and conform selected. The pre-bodyslide mesh works in game but after building it causes a crash in-game, it displays in OS and Bodyslide.

The crash logs seems to indicate that something went wrong will working with the partitions.

The three stages of mesh
[ShapeData.zip](https://github.com/ousnius/BodySlide-and-Outfit-Studio/files/8360036/ShapeData.zip)

Crash Log
[crash-2022-03-28-06-20-03.log](https://github.com/ousnius/BodySlide-and-Outfit-Studio/files/8360090/crash-2022-03-28-06-20-03.log)

**Comment by ousnius** [comment]
@JunktownJerkyVendor Thanks for the detailed report. However, this isn't a bug with BodySlide or Outfit Studio.

You said you converted the NIF file using CAO, I'm assuming from LE to SE. However, while the file version of the NIF file was changed from 83 (LE) to 100 (SE), the shapes are all still NiTriShape instead of BSTriShape.

This isn't expected and generally shouldn't be done especially for skinned meshes (SE version but still using NiTriShape), so BodySlide doesn't handle it correctly and some things are being calculated as if it was a BSTriShape block instead.

**Comment by JunktownJerkyVendor** [comment]
I see, but since it works in-game shouldn't this suite, support a configuration that the game supports?

**Comment by ousnius** [comment]
I've brainstormed this a few times now, but it's too messy to add support for saving out this combination properly (SSE version with a skinned NiTriShape), so I won't be doing it right now.

Closing this for now.
