### ISSUE TITLE
When Exporting to Nif BSEffectShaderPropertyFloat does not link it's target correctly when using merge geometry

### ISSUE THREAD

**Issue by CyborgArmGun** [ousnius/BodySlide-and-Outfit-Studio#465]
**Description**
If you take two BSEffectShaderProperty of the same type and merge, then save. Exporting to nif and running bodyslide produces the same result.

**How to reproduce**
1. Click on 'merge geometry'
2. Set either as the base
3. Save
4. View in NifSkope and the BSEffectShaderPropertyFloat will not list it's BSEffectShaderProperty as it's target.

Image Example:

![Ground object ctd](https://user-images.githubusercontent.com/19655256/188798005-109cc69f-cbb9-441d-81d4-43e346d79d55.jpg)

**Comment by vometia** [comment]
Just run into this one myself (and with exactly the same piece of armour too!)  Fortunately it's easy enough to fix, it's remembering to do it before the game reminds me by crashing that's the difficult bit...

**Comment by ousnius** [comment]
@CyborgArmGun @vometia The issue comes from duplicating the shape (or separating vertices), where it's not updating the block index in the BSEffectShaderPropertyFloat to point to the duplicated BSEffectShaderProperty.

Deleting the original shape when merging together, it will update the wrong index of the now deleted shape to be empty.
I fixed the issue, but there is currently no new release of Outfit Studio in the pipeline at the time of writing.

**Comment by vometia** [comment]
Not sure if it's important, but I run into the same thing without doing a merge: loading, doing some minor faffing about (just minor sculpting, no vertex separation I don't think), conform, save still has the BSEffectShaderPropertyFloatController with an empty target.  Or perhaps more worryingly a random one.  Though judging by your explanation I guess it's probably covered by the fix anyway.

**Comment by CyborgArmGun** [comment]
One can hope, just glad this is being addressed.

**Comment by ousnius** [comment]
> Not sure if it's important, but I run into the same thing without doing a merge: loading, doing some minor faffing about (just minor sculpting, no vertex separation I don't think), conform, save still has the BSEffectShaderPropertyFloatController with an empty target. Or perhaps more worryingly a random one. Though judging by your explanation I guess it's probably covered by the fix anyway.

I couldn't get the target to become empty or random when I was messing around with adding, deleting, reordering or editing shapes. So the issue might also arrise from something else I didn't try to do.

The fix I just did is definitely only related to copying or duplicating shapes or shaders, though.

**Comment by vometia** [comment]
I should run through it again to work out what it is I'm doing.  I won't be entirely surprised if it turns out to be something really obscure, my approach to working on things is, erm... well, "idiosyncratic" to put it politely.  And I seem to have a habit of making work for myself.

Edit: lack-of-concentration induced typo.
