### ISSUE TITLE
Merging shapes with different vertice counts.

### ISSUE THREAD

**Issue by lensman11** [ousnius/BodySlide-and-Outfit-Studio#475]
How hard is it to provide the option above. Have often used the seperate vertice/blocks but after making changes was not able to re-combine them.  Is there a process hidden in the menu options which already does this like the "Refine Messes feature' which you recently helped me with.
I use Metasequia a lot to do many of these functions but it loses the texture links when exporting/importing meshes and occassionally messes up the normals [sometime un-retrievably].
Outfit Studio is great when you know how to use it but managing messes still seems to lag behind.

Regards Colin.

**Comment by ousnius** [comment]
@lensman11 "Shape -> Merge Geometry" lets you merge one shape into another.
They have to have matching partitions slots and textures for it to work.

**Comment by lensman11** [comment]
Can the merge function include meshes of differing vertice counts?
The odvious issue I see is the textures may mis-match. Adding/merging meshes to my limited knowledge should be ok.
I would see the need to use an external app like metasequia [as I do] to reset/merge textures. Or using photoshop or something similar.
Surely there is a solution to this request even if it involves the use of other apps to support it.

Regards Colin.

**Comment by ousnius** [comment]
Vertex count has nothing to do with merging shapes. Have you actually tried the functionality? You should see quickly what it does and doesn't do.

**Comment by lensman11** [comment]
I appologise if I appear to be harping on this point somewhat but if the partition and textures have to "match" then what would be the use of a merge function at all?
I have used the merge function to combine left/right sides [mirrored] meshes but seemed blocked when wanting to combine other meshes which may share textures BUT NOT vertex counts [unsure what you noted about vertex counts not being relevent].
regards Colin

**Comment by jbostrus** [comment]
@lensman11 Think about it. You're trying to combine multiple shapes to be one shape. If you are editing a shape what options do you have. You can only specify 1 texture per shape. So as a safety mechanism OS prevents you from screwing yourself over in that regard. Since shapes that would have different textures would potentially have conflicting UV maps the merging of textures you suggested previously doesn't really work.

I'm not familiar with Metasequia or the workflow involved with it. But if you're exporting/importing from obj or fbx then a lot of relevant data may be lost. Since you mentioned you're basically splitting a shape doing editing and then bring it back in. Then after getting it back into OS you would need to manually repair that (textures and partitions) before trying to merge. At which point you should be good to go.

The merging limitations has nothing to do with vertex counts.

**Comment by lensman11** [comment]
I thank you for being so patient with this - I take notice of what you say.
Just an FYI...
I export meshes as .OBJ to meta - do mesh changes as the features allow - import back to Outfit Studio.
I have found, most times the only thing lost is the texture pointers which I copy from the original .nif entries and "good to go".
I have had a lot of satifying results including mesh merging, mesh splitting and mirroring.

PS: Just an enquiry - previous request for a user config or equivalent - any indication of when if ever that may be available?
Regards Colin
