### ISSUE TITLE
bugs with bodyslide outfit studio for oblivion

### ISSUE THREAD

**Issue by BakaNakama** [ousnius/BodySlide-and-Outfit-Studio#505]
**Description**
1 when you export/ save a mesh after deleting or merging a mesh it changes the skin instance from niskininstance to bsdismemberskininstance making the mesh invisible in game
 
2 when you copy bone weight for the upperbody the neck node nestles inside of the toe node. breaking the neck bone in game, but not nifscope :Edit: this will only occur if the outfit has both upper and lower portion

3 when you use a slider on the lower body it causes a seam. why? i dont know, but if you set base shape in outfit studio and mirror the mesh x and then x again before you export/save the mesh, the seam will go away :edit: this also happens when you build a body, or outfit showing skin in bodyslide. Once you save it the seam won't go away

**Comment by VKVII** [comment]
I have experienced the first one a lot and thanks for the heads up about the other two issues.  

I hope it will get fixed, in the meantime, about the first issue, I do this:
open the exported file in Nifskope, right click on the BSDismemberSkinInstance ---> Block---> Convert ---> NiSkinInstance.
May be useful to someone.

**Comment by ousnius** [comment]
@BakaNakama @VKVII I fixed the first issue, but couldn't reproduce the second issue. Maybe I need a specific NIF you are using as the reference body and as the outfit.

About issue 3, maybe this is related to normals being recalculated for the mesh? You could try locking normals in the project in Outfit Studio before using it in BodySlide (Shape -> Lock Normals). Otherwise I would need a specific project I can test with where the issue is happening.
