### ISSUE TITLE
Redo OpenGL views with wxGLCanvas

### ISSUE THREAD

**Issue by ousnius** [ousnius/BodySlide-and-Outfit-Studio#51]
The BodySlide and Outfit Studio OpenGL views should be redone with wxGLCanvas for more consistency.

**Comment by orxx** [comment]
I have a commit which switches the preview window to wxGLCanvas at orxx@2366b94b4ca98f7dbdb7271642c8776093dd2496

There is still one minor issue with texture loading that I haven't addressed: textures pop in after the window opens, rather than loading immediately.

This branch also contains a number of other minor fixes and enhancements that I separated out from the Linux port.

**Comment by ousnius** [comment]
Thanks, I've already taken a look at your various changes in the other branches. I've copied your wx branch now, seems to work.

The textures popping up happens in my normal branch as well. I think it might have something to do with SOIL.
