### ISSUE TITLE
Issues with reference with two sources for slider data

### ISSUE THREAD

**Issue by jbo18** [ousnius/BodySlide-and-Outfit-Studio#510]
**Description**
I cannot replace the CBBE reference shape in an outfit with a different one that has additional sliders.
Every time I attempt this, only CBBE slider data remains - any new sliders added don't do anything after the outfit is saved and re-opened.
I have tried deleting slider data, deleting sliders, and deleting both sliders *and* slider data and nothing seems to solve the issue,

This forces me to unmark the CBBE shape as a reference, then I have to load the other various references needed and conform one by one, then load the desired final reference body and conform the CBBE body to it. I then have to mark CBBE as reference again and delete  any other shapes that were used as references. This is very tedious.

**How to reproduce**
Open any CBBE outfit that contains the CBBE base body.
Replace the reference with the one you want to have in the outfit (in my case True Wasteland Body)
Conform sliders.
Save -> unload project -> load the project that was just saved
Only CBBE sliders will work - new sliders will not do anything to the base reference body shape.

**Comment by ousnius** [comment]
@jbo18 Sorry for the late response. So I tested various things with regular CBBE and with TWB.

This behaviour is caused by TWB loading the original CBBE sliders from the file "ShapeData\CBBE\CBBEBody.osd" and its additional sliders from the file "ShapeData\The Wasteland Body\The Wasteland Body.osd". The latter of which is what the project refers to as the "local" file (it's the OSD of the project) and the CBBE one is an "external" file that is referenced for by the TWB project.

When you load this TWB reference and use it to save an outfit project, the "local" shapedata folder won't be the "The Wasteland Body" folder anymore, but the folder of the outfit, which doesn't contain the OSD file of TWB. This is why the body "loses" the TWB slider data.

This also happens when you load the TWB reference the normal way and create a conversion. People have worked around this issue by renaming the TWB shape in Outfit Studio before saving, as this duplicates the slider data into the outfit's own slider data, which makes it work for all sliders.

Right now this is the only thing that comes to my mind that will do as a workaround, as there can only be one "local" folder in a project.

**Comment by ousnius** [comment]
I've just added support for multiple data folders when using a reference for a new project.

Previously, when a reference was loaded that referenced external extra sliders in addition to the slider data in its local folder, it would lose the link to those when saved as a new project.

Now, both data folders are added to the reference shape in the resulting outfit project, so the link to both .osd file sources stays intact.

So with TWB it uses ``CBBE\CBBEBody.osd`` and ``The Wasteland Body\The Wasteland Body.osd`` in the reference, and when you use the TWB reference for an outfit project and save, it will now list both folders in the project, and all sliders keep working without the rename trick.

```xml
<Shape target="True Wasteland Body" DataFolder="CBBE;True Wasteland Body">True Wasteland Body</Shape>
```
